apiVersion: v1
kind: ConfigMap
metadata:
  name: taskflow-config
  namespace: taskflow
  labels:
    app.kubernetes.io/name: taskflow-config
    app.kubernetes.io/part-of: taskflow-devops
data:
  PORT: "5000"
  NODE_ENV: "production"
  MONGODB_URI: "mongodb://mongodb-service:27017/taskflow"
  CORS_ORIGIN: "*"
